workflows:
  firebase-app-workflow:
    name: Firebase app workflow
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Build apk
        script: flutter build apk --release
    publishing:
      slack:
        channel: '#codemagic_builds'
        notify_on_build_start: true
        notify:
          success: true
          failure: true