workflows:
  firebase-app-workflow:
    name: Firebase app workflow
    max_build_duration: 30
    scripts:
      - name: Get Flutter Packages
        script: flutter packages pub get
      - name: Build apk
        script: flutter build apk --release
      - name: Build ios
        script: flutter build ios
    publishing:
      slack:
        channel: '#codemagic_builds'
        notify_on_build_start: true
        notify:
          success: true
          failure: true